spring.application.name=devoir

#spring.datasource.url=jdbc:postgresql://localhost:5432/gl
#spring.datasource.username=agromav
#spring.datasource.password=agromav
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.profiles.active=prod

#spring.sql.init.mode=always

#Si vous voulez tester rapidement l'application modifier cette valeur d'attribut en 'update'
#puis copier le code sql du fichier init-data.sql et inserer le dans la console de requete sql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.packages-to-scan=com.devoir.controllers
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

#Config de postgres pour assurer de gros volumes
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=2000

#Limiter le nombre de requete sur les api
resilience4j.ratelimiter.instances.userApi.limitForPeriod=50
resilience4j.ratelimiter.instances.userApi.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.userApi.timeoutDuration=0